CREATE CACHED TABLE PUBLIC.HISTORY( 
    SONGID INT SELECTIVITY 12, 
    PLAY_TIME DATETIME SELECTIVITY 1, 
    IS_COMPLETED BOOLEAN SELECTIVITY 30 
);

UPDATE CONFIG SET VALUE='1' WHERE NAME='LAST_RUN_SCRIPT';